export const API = {
  NFT: "/nfts/owner",
  PET: "/pet/get",
  ITEM_APP_OWNER: "/itemAppOwners",
  ITEM_GAME_OWNER: "/itemGameOwners",
  ITEM_GAME: "/itemGames",
  ITEM_APP: "/itemApps",
  HANG_MAN: "/hangmans",
  USERS: "users",
  BREED: "/bears/breed",
  CUP: "/cups",
  BOOST_EFFECTS: "/boostEffects",
  server: "https://gamefi-hcmus-aq3q.onrender.com/",
  BOOSTEFFECT: "/boostEffects",
};
