module.exports={
	adminRouter:require("./adminRouter"),
	bearRouter:require("./bearRouter"), 
	eyePoolRouter:require("./eyePoolRouter"), 
	elementPoolRouter:require("./elementPoolRouter"), 
	furPoolRouter:require("./furPoolRouter"), 
	itemPoolRouter:require("./itemPoolRouter"), 
	nftRouter:require("./nftRouter"),
	tokenUriRouter:require("./tokenUriRouter"),
	itemGameRouter:require("./itemGameRouter"),
	itemAppRouter:require("./itemAppRouter"),
	itemGameOwnerRouter:require("./itemGameOwnerRouter"),
	itemAppOwnerRouter:require("./itemAppOwnerRouter"),
}