module.exports={
	adminRouter:require("./adminRouter"),
	bearRouter:require("./bearRouter"), 
	nftRouter:require("./nftRouter"),
	tokenUriRouter:require("./tokenUriRouter"),
	itemGameRouter:require("./itemGameRouter"),
	itemAppRouter:require("./itemAppRouter"),
	itemGameOwnerRouter:require("./itemGameOwnerRouter"),
	itemAppOwnerRouter:require("./itemAppOwnerRouter"),
}